export default {
  title: "zerm (Eleventy Port)",
  description: "Eleventy 3.1.5 + Luxon port of the Zola zerm theme.",
  language: "en",
  author: "elias julian marko garcia",
  url: "https://example.com",
  themeSlug: "zerm",
  themeName: "zerm",
  themeHomepage: "https://github.com/ejmg/zerm",
  themeDemo: "https://zerm.ejmg.now.sh/",
  themeAuthor: "elias julian marko garcia",
  themeLicense: "MIT",
  hasSearch: true,
  styles: ["/style.css", "/color/green.css"],
  navigation: [
    { label: "Home", url: "/" },
    { label: "Blog", url: "/blog/" },
    { label: "About", url: "/about/" },
    { label: "Contact", url: "/contact/" },
  ],
  favicons: [
    { rel: "icon", href: "/favicon.png", type: "image/png" },
    { rel: "icon", href: "/favicon-32x32.png", type: "image/png", sizes: "32x32" },
    { rel: "apple-touch-icon", href: "/apple-touch-icon.png" },
  ],
  contributors: [
    "elias <elias.jm.garcia@gmail.com>",
    "damccull <damccull+git@gmail.com>",
    "Austin Dworaczyk Wiltshire <561689+adworacz@users.noreply.github.com>",
    "Kartavya Vashishtha <sendtokartavya@gmail.com>",
    "Leo Di Donato <leodidonato@gmail.com>",
    "Cromo <56557525+gicrisf@users.noreply.github.com>",
    "Eyal Kalderon <ebkalderon@gmail.com>",
    "p-inks <usedprivacy@gmail.com>",
    "Abhik Jain <abhikjain360@gmail.com>",
    "Austin Wise <AustinWise@gmail.com>",
    "Cromo <56557525+mr-chrome@users.noreply.github.com>",
    "Dan Baker <daniel.n.baker@gmail.com>",
    "David Siher <32305650+dsiher@users.noreply.github.com>",
    "Taryn Hill <taryn@phrohdoh.com>",
  ],
  coauthors: ["Daniel Baker <daniel.baker@tweag.io>"],
};
